name: siralim-ultimate-api-ci
on:
  push:
    branches:
      - main
jobs:
  heroku:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push nginx
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        working-directory: ./nginx
        run: heroku container:push --app ${{ secrets.HEROKU_NGINX_NAME }} web
      - name: Release nginx
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        working-directory: ./nginx
        run: heroku container:release --app ${{ secrets.HEROKU_NGINX_NAME }} web
            